name: build

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: |
        dnf -y install 'dnf-command(builddep)'
        dnf -y builddep gnutls
        dnf -y install autoconf autogen-libopts-devel automake bison gcc-c++ gettext-devel git gperf libev-devel libtool make meson ninja-build patch wget
    - name: install nghttp3
      run: |
        git clone --depth=1 https://github.com/ngtcp2/nghttp3.git
        cd nghttp3
        autoreconf -i
        ./configure --prefix=$PWD/../installdir --enable-lib-only
        make -j$(nproc)
        make install
        cd ..
    - name: install gnutls
      run: |
        git clone --depth=1 https://gitlab.com/gnutls/gnutls.git
        cd gnutls
        ./bootstrap
        ./configure --disable-doc --disable-guile --prefix=$PWD/../installdir
        make -j$(nproc)
        make install
        cd ..
    - name: install ngtcp2
      run: |
        git clone --depth=1 https://github.com/ngtcp2/ngtcp2.git
        cd ngtcp2
        autoreconf -i
        PKG_CONFIG_PATH=$PWD/../installdir/lib/pkgconfig ./configure --prefix=$PWD/../installdir --enable-lib-only
        make -j$(nproc)
        make install
        cd ..
    - name: build
      run: |
        git clone --depth=1 https://github.com/nodejs/http-parser.git
        PKG_CONFIG_PATH=$PWD/installdir/lib/pkgconfig meson _build
        ninja -C _build
